sudo: required
services:
  - docker

before_install:
  - docker build -t bhagwat13/frontend-prod -f Dockerfile  .

scripts:
  - docker run -e CI=true bhagwat13/frontend-prod npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app2"
  env: "Docker-react-app2-env"
  bucket_name: "elasticbeanstalk-us-east-2-782570631763"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
